apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdb
  namespace: mboukraa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webdb
  template:
    metadata:
      labels:
        app: webdb
    spec:
      containers:
      - name: webdb
        image: meriambkrr/challenge4-flask-nodb:v1
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 1
