apiVersion: v1
kind: Service
metadata:
  name: webdb-service
  namespace: mboukraa
spec:
  selector:
    app: webdb
  ports:
    - protocol: TCP
      port: 5000       # Port interne du service
      targetPort: 5000 # Port du pod webdb
  type: ClusterIP

