apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdb
spec:
  replicas: {{ .Values.webdb.replicas }}
  selector:
    matchLabels:
      app: webdb
  template:
    metadata:
      labels:
        app: webdb
    spec:
      containers:
        - name: webdb
          image: {{ .Values.webdb.image }}
          ports:
            - containerPort: {{ .Values.webdb.port }}

          env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: MONGO_PORT

          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "200Mi"
